from . import views
from django.urls import path


app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('faust1/', views.faust1, name='faust1'),
    path('faust2/', views.faust2, name='faust2'),
    path('faust3/', views.faust3, name='faust3'),
    path('faust4/', views.faust4, name='faust4'),
    path('faust5/', views.faust5, name='faust5'),
    path('faust6/', views.faust6, name='faust6'),
    path('faust7/', views.faust7, name='faust7'),
    path('faust8/', views.faust8, name='faust8'),
    path('faust9/', views.faust9, name='faust9'),
    path('collage/', views.collage, name='collage'),
    path('collage/1/', views.collage1, name='collage1'),
    path('collage/2/', views.collage2, name='collage2'),
    path('collage/3/', views.collage3, name='collage3'),
    path('collage/4/', views.collage4, name='collage4'),
    path('collage/5/', views.collage5, name='collage5'),
    path('collage/6/', views.collage6, name='collage6'),
    path('collage/7/', views.collage7, name='collage7'),
    path('collage/8/', views.collage8, name='collage8'),
    path('collage/9/', views.collage9, name='collage9'),
    path('collage/10/', views.collage10, name='collage10'),
    path('collage/11/', views.collage11, name='collage11'),
    path('collage/12/', views.collage12, name='collage12'),
    path('painting/', views.painting, name='painting'),
    path('painting/1/', views.painting1, name='painting1'),
    path('painting/2/', views.painting2, name='painting2'),
    path('painting/3/', views.painting3, name='painting3'),
    path('painting/4/', views.painting4, name='painting4'),
    path('painting/5/', views.painting5, name='painting5'),
    path('painting/6/', views.painting6, name='painting6'),
    path('painting/7/', views.painting7, name='painting7'),
    path('painting/8/', views.painting8, name='painting8'),
    path('painting/9/', views.painting9, name='painting9'),
    path('painting/10/', views.painting10, name='painting10'),
    path('pastel/', views.pastel, name='pastel'),
    path('pastel/1/', views.pastel1, name='pastel1'),
    path('digital/', views.digital, name='digital'),
    path('digital/1/', views.digital1, name='digital1'),
    path('artist_note/', views.artist_note, name='artist_note'),
    path('about/', views.about, name='about'),
]